# Generated by Django 3.2.8 on 2021-12-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crowling_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(default='', max_length=10)),
                ('taste', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=1000)),
                ('delivery', models.CharField(default='', max_length=1000)),
                ('com_name', models.CharField(default='', max_length=100)),
                ('com_time', models.CharField(default='', max_length=100)),
                ('order_menu', models.CharField(default='', max_length=1000)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('com_picture_1', models.CharField(default='', max_length=1000)),
                ('com_picture_2', models.CharField(default='', max_length=1000)),
                ('com_picture_3', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'crowling_all',
            },
        ),
        migrations.CreateModel(
            name='eventModel',
            fields=[
                ('review_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=256)),
                ('date', models.CharField(default='', max_length=256)),
                ('label', models.CharField(default='', max_length=256)),
                ('star', models.CharField(default='', max_length=10)),
                ('expectedPoint', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Rest_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_point', models.FloatField(default=0, null=True)),
                ('star', models.CharField(default='', max_length=10)),
                ('expected_star_point', models.FloatField(default=0, null=True)),
                ('expected_star', models.CharField(default='', max_length=10)),
                ('rest_name', models.CharField(default='', max_length=100)),
                ('review_notice', models.CharField(default='', max_length=1000)),
                ('pic', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'Rest_Info',
            },
        ),
        migrations.CreateModel(
            name='SimilarComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(default='', max_length=10)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('preprocessingComment', models.CharField(default='', max_length=1000)),
                ('similarComment1', models.CharField(default='', max_length=1000)),
                ('similarity1', models.FloatField(default=0, null=True)),
                ('similarComment2', models.CharField(default='', max_length=1000)),
                ('similarity2', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'SimilarComment',
            },
        ),
        migrations.CreateModel(
            name='sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('expectedPoint', models.FloatField(default=0, null=True)),
                ('similarComment1', models.CharField(default='', max_length=1000)),
                ('similarComment2', models.CharField(default='', max_length=1000)),
                ('label', models.CharField(max_length=256)),
                ('star', models.IntegerField(default=0, null=True)),
                ('comment', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'sorting',
            },
        ),
    ]
